// Rebuild data/cities.ts from the GeoNames dump (https://download.geonames.org/export/dump/):
//   cities15000.zip (unzipped), admin1CodesASCII.txt, countryInfo.txt
// Usage: node build-cities.cjs <cities.txt> <admin1CodesASCII.txt> <countryInfo.txt> <out.ts>
const fs = require("fs");
const [citiesPath, adminPath, countryPath, outPath] = process.argv.slice(2);

const countries = {};
for (const line of fs.readFileSync(countryPath, "utf8").split("\n")) {
  if (!line || line.startsWith("#")) continue;
  const f = line.split("\t");
  if (f[0] && f[4]) countries[f[0]] = f[4];
}

const admin1 = {};
for (const line of fs.readFileSync(adminPath, "utf8").split("\n")) {
  const f = line.split("\t");
  if (f[0] && f[1]) admin1[f[0]] = f[1];
}

// Drop city sections and historical/abandoned/destroyed places — they are
// districts or ghosts, not birthplaces, and they crowd the search results.
const SKIP = new Set(["PPLX", "PPLH", "PPLQ", "PPLW", "PPLCH"]);

const rows = [];
for (const line of fs.readFileSync(citiesPath, "utf8").split("\n")) {
  if (!line) continue;
  const f = line.split("\t");
  if (SKIP.has(f[7])) continue;
  const tz = f[17];
  if (!tz) continue;
  rows.push({
    name: f[1],
    ascii: f[2],
    cc: f[8],
    a1: f[10],
    lat: Number(f[4]),
    lon: Number(f[5]),
    pop: Number(f[14]) || 0,
    tz,
  });
}

// Biggest first: search returns matches in this order, so "London" yields the
// UK capital before London, Ontario.
rows.sort((a, b) => b.pop - a.pop);

const tzList = [...new Set(rows.map(r => r.tz))].sort();
const tzIndex = new Map(tzList.map((t, i) => [t, i]));

const usedAdmin = {};
const usedCountry = {};
const lines = rows.map(r => {
  const adminKey = `${r.cc}.${r.a1}`;
  if (admin1[adminKey]) usedAdmin[adminKey] = admin1[adminKey];
  if (countries[r.cc]) usedCountry[r.cc] = countries[r.cc];
  // ascii column left empty when identical to the name, to save space
  const ascii = r.ascii && r.ascii !== r.name ? r.ascii : "";
  return [r.name, ascii, r.cc, r.a1, r.lat.toFixed(2), r.lon.toFixed(2), tzIndex.get(r.tz)].join("\t");
});

const out = `/* eslint-disable */
// GENERATED by scripts/build-cities.cjs — do not edit by hand.
// City data © GeoNames (https://www.geonames.org), licensed CC BY 4.0.
// ${rows.length} places with population >= 15,000, sorted by population.
// Row format: name \t asciiName \t countryCode \t admin1Code \t lat \t lon \t tzIndex

export const TIMEZONES: string[] = ${JSON.stringify(tzList)};

export const COUNTRIES: Record<string, string> = ${JSON.stringify(usedCountry)};

export const ADMIN1: Record<string, string> = ${JSON.stringify(usedAdmin)};

export const CITY_ROWS: string = ${JSON.stringify(lines.join("\n"))};
`;
fs.writeFileSync(outPath, out);
console.log(`${rows.length} places, ${tzList.length} timezones, ${Object.keys(usedCountry).length} countries -> ${(out.length / 1024 / 1024).toFixed(2)} MB`);
